# Site settings
title: 马一特 - Albert Ma
SEOTitle: 马一特个人主页
email: yitema01@gmail.com
description: "马一特个人主页"
keyword: "马一特"
url: "https://mayite.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mayite/mayite.github.io.git" # you code repository
